version: '3'
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    networks:
      - mi_red

  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge
