version: '3.8'

services:
  # Servicio Web
  web:
    build: ./web
    ports:
      - "8080:80"
    networks:
      - mi_red

  # Servicio API
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - mi_red

  # Servicio Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - mi_red

# Red de contenedores
networks:
  mi_red:
    driver: bridge

# Volúmenes
volumes:
  jenkins_home: